// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using webapi.Models;

namespace webapi.Models
{
    public partial interface IMyLocalDBContextProcedures
    {
        Task<int> AddMonthlyRevenueSummaryAsync(string ReportDate, string DataYearMonth, string CompanyCode, string CompanyName, string Industry, long? CurrentRevenue, long? LastMonthRevenue, long? LastYearSameMonthRevenue, double? MonthlyChangePercent, double? YearlyChangePercent, long? CumulativeCurrentRevenue, long? CumulativeLastYearRevenue, double? CumulativeChangePercent, string Remarks, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetMonthlyRevenueSummaryResult>> GetMonthlyRevenueSummaryAsync(string CompanyCode, string DataYearMonth, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
