// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webapi.Models
{
    public partial class MonthlyRevenueSummary
    {
        [Required]
        [StringLength(7)]
        public string ReportDate { get; set; }
        [Key]
        [StringLength(6)]
        public string DataYearMonth { get; set; }
        [Key]
        [StringLength(10)]
        public string CompanyCode { get; set; }
        [Required]
        [StringLength(50)]
        public string CompanyName { get; set; }
        [Required]
        [StringLength(50)]
        public string Industry { get; set; }
        public long CurrentRevenue { get; set; }
        public long LastMonthRevenue { get; set; }
        public long LastYearSameMonthRevenue { get; set; }
        public double? MonthlyChangePercent { get; set; }
        public double? YearlyChangePercent { get; set; }
        public long CumulativeCurrentRevenue { get; set; }
        public long CumulativeLastYearRevenue { get; set; }
        public double? CumulativeChangePercent { get; set; }
        public string Remarks { get; set; }
    }
}